### ISSUE TITLE
multiple strips

### ISSUE THREAD

**Issue by lokkiikkol** [MrYsLab/NeoPixelConnect#9]
hi there,

can i use your library to address more then one LED-strip? could you elaborate a little, if i need to choose another pio or i can use the same for multiple strips? Is there a maximum of strips i can use? I would like to control them all individually. (different animations, timing and colors etc.)

**Comment by MrYsLab** [comment]
I have not tested this, but I believe it should work. Essentially, you would create an instance of NeoPixelConnect for each strip and assign each a unique pin number. The number of strips would be limited to available pins on the RP2040.

For example:
// strip1 connected to pin 4
NeoPixelConnect strip1(4, MAXIMUM_NUM_NEOPIXELS_STRIP1, pio0, 0);

// strip2 connected to pin 5
NeoPixelConnect strip1(5, MAXIMUM_NUM_NEOPIXELS_STRIP2, pio0, 0);

You may need to add appropriate wait times when going from one strip to another.

**Comment by lokkiikkol** [comment]
this is great news, i will test this in the next few days. the constructor in your example should read strip2(etc....) for the second strip i guess :-) I was mainly unsure about using the same pio0 for all strips, but that seems to be ok.

**Comment by MrYsLab** [comment]
You can name each instance anything you wish. For the examples, I name the instance [p.](https://github.com/MrYsLab/NeoPixelConnect/blob/1ddf7e001825c46913788ec990bb459d44122bd8/examples/fireworks/fireworks.ino#L25)

**Comment by lokkiikkol** [comment]
sorry I was not clear :-) yes I understand this... however you cannot call two instances by the same name, which you did (accidentally) in your example. (strip1 and strip1) I just wanted to point that out for future reference.

**Comment by MrYsLab** [comment]
Sorry. Cut, paste, and old age error ;-)

**Comment by lokkiikkol** [comment]
_I tried this and unfortunately all strips stop working as soon as i put more then one instance of NeoPixelConnect in the code. There is no error, the code uplaods fine, but all the strips stay black._ EDIT: correction, the last defined strip keeps working, all others are black.

**Comment by lokkiikkol** [comment]
here is what seems to be a multiple output example, from the code you based this off: https://github.com/raspberrypi/pico-examples/blob/master/pio/ws2812/ws2812_parallel.c but i don't know if that helps...

**Comment by MrYsLab** [comment]
Thanks for the link. I do not fully understand the parallel example since it uses DMA, and I am unsure of its significance.

In the meantime, there are a couple of things you can try.

Using this [constructor](https://github.com/MrYsLab/NeoPixelConnect/blob/1ddf7e001825c46913788ec990bb459d44122bd8/src/NeoPixelConnect.h#L56) first, try one strip using pio0 and a second strip using pio1. If this works, it will limit the maximum number of NeoPixel strips to 2, but I just want to see if the problem exists when using two PIOs.

Next, using pio0 for both strips, change the sm parameter for each instance.
Each PIO has four state machines (sm), and if that works, then there is potential support for a maximum of 8 strips.

**Comment by lokkiikkol** [comment]
Thanks for your insights, and sorry for the delay. I cannot test the different pio's at the moment, since i use pio0 for dmx input, but i can confirm that i can control multiple strips by using different state machines for each strip. so in my case i can control up to 4 strips per pico with dmx input. Since the pio's and sm's "emulate" the ws2812 protocol I guess there is no way to lift that limitation, right?

**Comment by MrYsLab** [comment]
If a maximum of four strips is insufficient, you might try the [Adafruit NeoPixel library](https://github.com/adafruit/Adafruit_NeoPixel). I have never used this library, but supposedly, it will handle as many strips as there are free I/O pins available.

I will close the issue, but if you have any additional comments or questions, please post them here.

**Comment by lokkiikkol** [comment]
thanks again, but i'd rather use this library :-) also i think the same limitations apply there as well (from the neopixel github): "There is a maximum of 8 neopixel strands, if pio and sm's are not used for any other purposes in your project. Strands can be assigned to any GPIO pin of the pico."

**Comment by MrYsLab** [comment]
I know that [setting up a build environment for the RP2040](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf) can be painful, but I was wondering if you built and ran the ws2812_parallel example and if it can run with more than two strips.

If the example code is modified to run your required number of strips and runs successfully, I would be willing to investigate whether I can incorporate it into this library. Since the use of DMA is a mystery to me, it may take a while to understand the code. No promises, but I can try giving it a shot if the published example code can be modified to work to your satisfaction.
